# Generated by Django 5.2.6 on 2025-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="uploads/"
            ),
        ),
    ]
